CREATE TABLE IF NOT EXISTS frames (
    id INTEGER PRIMARY KEY,
    orig_tar_path TEXT,
    orig_frame_num INTEGER,
    orig_entry_id INTEGER,
    game_timestamp REAL,
    robot_state INTEGER,
    ball_x REAL,
    ball_y REAL,
    ball_w REAL,
    ball_h REAL,
    goal_x REAL,
    goal_y REAL,
    goal_w REAL,
    goal_h REAL,
    line_sensors TEXT,
    heading REAL,
    motor_values TEXT,
    robot_x REAL,
    robot_y REAL,
    robot_count INTEGER,
    enemy_positions TEXT,
    hue_avg REAL,
    hue_std REAL,
    sat_avg REAL,
    val_avg REAL,
    md5 TEXT,
    chosen BOOLEAN,
    has_annotation BOOLEAN,
    UNIQUE(orig_tar_path, orig_frame_num)
);
